apiVersion: apps/v1
kind: Deployment
metadata:
  name: npmdev
  labels:
    app: npmdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npmdev
  template:
    metadata:
      labels:
        app: npmdev
    spec:
      volumes:
        - name: src
          hostPath:
            path: "//C/Users/17T2055F/Desktop/ayamati/otamesi/frontend"
            type: DirectoryOrCreate
      containers:
        - image: node:lts
          name: npmdev
          workingDir: /usr/src/app
          volumeMounts:
            - mountPath: /usr/src/app
              name: src
          ports:
            - containerPort: 8080
              name: npmdev
          command:
            - /bin/bash
          args:
            - -c
            - npm run serve
