FROM ubuntu:20.10

RUN apt update

RUN apt install -y build-essential cmake git libjson-c-dev libwebsockets-dev
RUN git clone https://github.com/tsl0922/ttyd.git
RUN cd ttyd && mkdir build && cd build && cmake .. && make && make install

CMD ["ttyd", "bash"]